version: "3.1"

networks:
  default:
    driver: bridge
services:
  frontend:
    image: frontend
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - REACT_APP_SERVER_URL=http://172.19.133.44:32552
      - REACT_APP_CALL_SERVER_URL=http://172.19.133.44:32552 
    networks:
     - default
